/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Beta;

import Controller.ReservaController;
import Controller.habitacionController;
import Controller.hcatController;
import Controller.tipo_usuController;
import Controller.usuarioController;
import Model.Reserva;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Davs
 */
public class examen extends javax.swing.JFrame {
    private DefaultTableModel dtm = new DefaultTableModel();
    private ReservaController rController = new ReservaController();
    private usuarioController uController = new usuarioController();
    private tipo_usuController tController = new tipo_usuController();
    private habitacionController hController = new habitacionController();
    private hcatController cController = new hcatController();

    /**
     * Creates new form examen
     */
    public examen() {
        initComponents();
        llenaTabla();
        //llenaLista();
    }
        public void llenaTabla()
    {
        dtm.addColumn("CODIGO");
        dtm.addColumn("IDUSUARIO");
        dtm.addColumn("IDHABITACION");
        dtm.addColumn("FECHA RESERVACION");
        dtm.addColumn("CHECK-IN");
        dtm.addColumn("CHECK-OUT");
        dtm.addColumn("DIAS DISPONIBLES");
        dtm.addColumn("ESTANCIA");
        dtm.addColumn("COSTO");
        dtm.addColumn("ESTADO");
        
        this.tbreserva.setModel(dtm);
    }                          
    
    public void llenaLista()
    {
        List<Reserva> lst = rController.ReservaController();
        dtm.setRowCount(0);
        for(int i=0;i<lst.size();i++)
        {

                Object[] vhb=new Object[10];
                vhb[0] = lst.get(i).getIdReserva();
                vhb[1] = lst.get(i).getIdUsuario();
                vhb[2] = lst.get(i).getIdHabitacion();
                vhb[3] = lst.get(i).getFechap();
                vhb[4] = lst.get(i).getFechai(); 
                vhb[5] = lst.get(i).getFechaf();
                vhb[6] = lst.get(i).getDiasr();
                vhb[7] = lst.get(i).getEstancia();
                vhb[8] = lst.get(i).getCoste();
                vhb[9] = lst.get(i).getEstadoR();
                
                dtm.addRow(vhb);
        }
            
        this.tbreserva.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbreserva = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dias = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbreserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbreserva);

        jLabel1.setText("Busqueda por dias:");

        btnbuscar.setText("BUSQUEDA");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        List<Reserva> lst = rController.Buscarporestancia(Integer.parseInt(this.dias.getText()));
        
        if(lst==null)
        {
            JOptionPane.showMessageDialog(this, "No hay reservas dentro de los rangos selecionados");
        }
        else
        {
            dtm.setRowCount(0);
            for(int i=0;i<lst.size();i++)
            {

                Object[] vhb=new Object[10];
                vhb[0] = lst.get(i).getIdReserva();
                vhb[1] = lst.get(i).getIdUsuario();
                vhb[2] = lst.get(i).getIdHabitacion();
                vhb[3] = lst.get(i).getFechap();
                vhb[4] = lst.get(i).getFechai(); 
                vhb[5] = lst.get(i).getFechaf();
                vhb[6] = lst.get(i).getDiasr();
                vhb[7] = lst.get(i).getEstancia();
                vhb[8] = lst.get(i).getCoste();
                vhb[9] = lst.get(i).getEstadoR();
                
                dtm.addRow(vhb);
            }
            
            this.tbreserva.setModel(dtm);   
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JTextField dias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbreserva;
    // End of variables declaration//GEN-END:variables
}
