/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectopoo2;
import Model.usuario;
import Services.usuarioRepository;
import javax.swing.JOptionPane;
import Controller.usuarioController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static java.sql.Types.NULL;
import javax.swing.JFrame;

/**
 *
 * @author Davs
 */
public class CrearCuenta extends javax.swing.JFrame {
    
    private usuarioController uController = new usuarioController();
    

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        setLocationRelativeTo(null);
        ValidarLogin();
        cerrar();
    }
        public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter()
            {
                public void windowClosing(WindowEvent e)
                {
                    confirmarsalida();
                }
            });
            this.setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public void confirmarsalida()
    {
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta seguro de regresar al inicio de sesion sin haber creado un usuario? ", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(valor==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(null, "Sera redireccionado al Inicio de sesion", "Redireccionamiento",JOptionPane.INFORMATION_MESSAGE);
            InicioSesion is = new InicioSesion();
            is.setVisible(true);
            this.dispose();
        }
    }
    
   StringBuilder camposIncorrectos = new StringBuilder();
   public void ValidarLogin()
   {
       camposIncorrectos.setLength(0);
       String pas = new String(txtnpas.getPassword());
       String pas2 = new String(txtnpas2.getPassword());
       
       
       if(txtnUsu.getText().isEmpty())
       {
            camposIncorrectos.append("- Usuario\n");
            labelusuario.setText("Campo obligatorio");
       }
       else
       {
           labelusuario.setText("✔");
       }
       
       if(txtncorreo.getText().isEmpty())
       {
           camposIncorrectos.append("- Correo\n");
           labelcorreo.setText("Campo obligatorio");
       }
       else if(!txtncorreo.getText().contains("@") || !txtncorreo.getText().contains(".com"))
       {
           camposIncorrectos.append("- Correo\n");
           labelcorreo.setText("Correo invalido");
       }
       else
       {
            labelcorreo.setText("✔");   
       }
       if(pas.isEmpty())
       {
           camposIncorrectos.append("- Contrasena\n");
           labelpas.setText("Campo obligatorio");
       }
       else
       {
           labelpas.setText("✔");
       }
       if(!pas.equals(pas2) || pas.isEmpty())
       {
           camposIncorrectos.append("- Contrasena\n");
           labelpas2.setText("No coinciden");
       }
       else
       {
           labelpas2.setText("✔");
       }
       if(txttelefono.getText().isEmpty())
       {
           camposIncorrectos.append("- Telefono\n");
           labeltel.setText("Campo obligatorio");
       }
       else if(txttelefono.getText().length()<9)
       {
           camposIncorrectos.append("- Telefono\n");
           labeltel.setText("Numero de telefono invalido");
       }
       else
       {
           labeltel.setText("✔");
       }
       if(txtdni.getText().isEmpty())
        {   
            camposIncorrectos.append("- DNI\n");
            labeldni.setText("Campo obligatorio");
        }
       else if(txtdni.getText().length()<8)
       {
           labeldni.setText("DNI Invalido");
       }
       else
       {
           labeldni.setText("✔");
       }
       if(comboG.getSelectedIndex()==0)
       {
           camposIncorrectos.append("- Genero\n");
           labelg.setText("Campo obligatorio");
       }
       else
       {
           labelg.setText("✔");
       }
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnUsu = new javax.swing.JTextField();
        labelusuario = new javax.swing.JLabel();
        labelcorreo = new javax.swing.JLabel();
        labelpas = new javax.swing.JLabel();
        labelpas2 = new javax.swing.JLabel();
        txtnpas2 = new javax.swing.JPasswordField();
        txtnpas = new javax.swing.JPasswordField();
        txtncorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnsign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        comboG = new javax.swing.JComboBox<>();
        labeltel = new javax.swing.JLabel();
        labeldni = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ingrese un Usuario:");

        txtnUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnUsuKeyReleased(evt);
            }
        });

        labelusuario.setText("*");

        labelcorreo.setText("*");

        labelpas.setText("*");

        labelpas2.setText("*");

        txtnpas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnpas2ActionPerformed(evt);
            }
        });
        txtnpas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnpas2KeyReleased(evt);
            }
        });

        txtnpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnpasActionPerformed(evt);
            }
        });
        txtnpas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnpasKeyReleased(evt);
            }
        });

        txtncorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtncorreoActionPerformed(evt);
            }
        });
        txtncorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtncorreoKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese su Correo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ingrese su contraseña:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Reescriba la contraseña:");

        btnsign.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnsign.setText("Registrarse");
        btnsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("¿Nuevo Usuario?");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ingrese su género:");

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelefonoKeyReleased(evt);
            }
        });

        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdniKeyReleased(evt);
            }
        });

        comboG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "M", "F" }));
        comboG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboGKeyReleased(evt);
            }
        });

        labeltel.setText("*");

        labeldni.setText("*");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Ingrese su telefono:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ingrese su dni:");

        labelg.setText("*");

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtncorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboG, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnpas2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnpas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelpas, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(labelpas2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(labeltel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labeldni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelusuario))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtncorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelcorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelpas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltel)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeldni)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(labelg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnpas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelpas2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnUsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnUsuKeyReleased
        ValidarLogin();
    }//GEN-LAST:event_txtnUsuKeyReleased

    private void txtnpas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnpas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnpas2ActionPerformed

    private void txtnpas2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnpas2KeyReleased
        // TODO add your handling code here:
        ValidarLogin();
    }//GEN-LAST:event_txtnpas2KeyReleased

    private void txtnpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnpasActionPerformed

    private void txtnpasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnpasKeyReleased
        // TODO add your handling code here:
        ValidarLogin();
    }//GEN-LAST:event_txtnpasKeyReleased

    private void txtncorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtncorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtncorreoActionPerformed

    private void txtncorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtncorreoKeyReleased
        // TODO add your handling code here:
        ValidarLogin();
    }//GEN-LAST:event_txtncorreoKeyReleased

    private void btnsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignActionPerformed
               // TODO add your handling code here:
        String pas = new String(txtnpas.getPassword());
        String pas2 = new String(txtnpas2.getPassword());
        ValidarLogin();
        
         if(txtnUsu.getText().isEmpty() || txtncorreo.getText().isEmpty() || pas.isEmpty() || pas2.isEmpty() || !pas2.equals(pas) || !txtncorreo.getText().contains("@") || !txtncorreo.getText().contains(".com") || txttelefono.getText().isEmpty() || txtdni.getText().isEmpty() || comboG.getSelectedIndex()==0 || txttelefono.getText().length()<9 || txtdni.getText().length()<8)
         {
            String mensaje = "Debe completar los siguientes campos correctamente:\n" + camposIncorrectos.toString();
            JOptionPane.showMessageDialog(null, mensaje, "Campos incorrectos", JOptionPane.WARNING_MESSAGE);
            
            
        }
        else
        {
            usuario usu = new usuario();
            usu.setTipo(1);
            usu.setUsuario(this.txtnUsu.getText());
            usu.setCorreo(this.txtncorreo.getText());
            usu.setContraseña(pas);
            usu.setTelefono(this.txttelefono.getText());
            usu.setDni(this.txtdni.getText());
            usu.setGenero(this.comboG.getSelectedItem().toString());
            uController.Añadir(usu); //Pasa el objeto con los datos escritos en el formulario/
            JOptionPane.showMessageDialog(null, "Gracias por regitrarse, se le rediccionara al inicio de sesion", "Redireccionamiento",JOptionPane.INFORMATION_MESSAGE);
            InicioSesion is = new InicioSesion();
            is.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btnsignActionPerformed

    private void txttelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyReleased
        // TODO add your handling code here:
        ValidarLogin();
    }//GEN-LAST:event_txttelefonoKeyReleased

    private void txtdniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyReleased
        // TODO add your handling code here:
        ValidarLogin();
    }//GEN-LAST:event_txtdniKeyReleased

    private void comboGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboGKeyReleased
        // TODO add your handling code here:
        ValidarLogin();
    }//GEN-LAST:event_comboGKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InicioSesion is = new InicioSesion();
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsign;
    private javax.swing.JComboBox<String> comboG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelcorreo;
    private javax.swing.JLabel labeldni;
    private javax.swing.JLabel labelg;
    private javax.swing.JLabel labelpas;
    private javax.swing.JLabel labelpas2;
    private javax.swing.JLabel labeltel;
    private javax.swing.JLabel labelusuario;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnUsu;
    private javax.swing.JTextField txtncorreo;
    private javax.swing.JPasswordField txtnpas;
    private javax.swing.JPasswordField txtnpas2;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
