/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.proyectopoo2;

import Model.Reserva;
import Controller.ReservaController;
import Controller.habitacionController;
import Controller.hcatController;
import Controller.tipo_usuController;
import Controller.usuarioController;
import Model.habitacion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Davs
 */
public class Reservas extends javax.swing.JInternalFrame {
    private DefaultTableModel dtm = new DefaultTableModel();
    private ReservaController rController = new ReservaController();
    private usuarioController uController = new usuarioController();
    private tipo_usuController tController = new tipo_usuController();
    private habitacionController hController = new habitacionController();
    private hcatController cController = new hcatController();

    /**
     * Creates new form Reservas
     */
    public Reservas() {
        initComponents();
        llenaTabla();
        llenaLista();
    }
    
    public void llenaTabla()
    {
        dtm.addColumn("CODIGO");
        dtm.addColumn("IDUSUARIO");
        dtm.addColumn("IDHABITACION");
        dtm.addColumn("FECHA RESERVACION");
        dtm.addColumn("CHECK-IN");
        dtm.addColumn("CHECK-OUT");
        dtm.addColumn("DIAS DISPONIBLES");
        dtm.addColumn("ESTANCIA");
        dtm.addColumn("COSTO");
        dtm.addColumn("ESTADO");
        
        this.tbreserva.setModel(dtm);
    }
    
    public void llenaLista()
    {
        List<Reserva> lst = rController.ReservaController();
        dtm.setRowCount(0);
        for(int i=0;i<lst.size();i++)
        {

                Object[] vhb=new Object[10];
                vhb[0] = lst.get(i).getIdReserva();
                vhb[1] = lst.get(i).getIdUsuario();
                vhb[2] = lst.get(i).getIdHabitacion();
                vhb[3] = lst.get(i).getFechap();
                vhb[4] = lst.get(i).getFechai(); 
                vhb[5] = lst.get(i).getFechaf();
                vhb[6] = lst.get(i).getDiasr();
                vhb[7] = lst.get(i).getEstancia();
                vhb[8] = lst.get(i).getCoste();
                vhb[9] = lst.get(i).getEstadoR();
                
                dtm.addRow(vhb);
        }
            
        this.tbreserva.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbreserva = new javax.swing.JTable();
        fechai = new javax.swing.JTextField();
        fechaf = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tbreserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbreserva);

        fechai.setText("00-00-0000");

        fechaf.setText("00-00-0000");

        btnbuscar.setText("BUSCAR ENTRE FECHAS");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jButton1.setText("LLENAR TABLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(fechaf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fechaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        List<Reserva> lst = rController.BuscarEntreFechas(fechai.getText(), fechaf.getText());
        
        if(lst==null)
        {
            JOptionPane.showMessageDialog(this, "No hay reservas dentro de los rangos selecionados");
        }
        else
        {
            dtm.setRowCount(0);
            for(int i=0;i<lst.size();i++)
            {

                Object[] vhb=new Object[10];
                vhb[0] = lst.get(i).getIdReserva();
                vhb[1] = lst.get(i).getIdUsuario();
                vhb[2] = lst.get(i).getIdHabitacion();
                vhb[3] = lst.get(i).getFechap();
                vhb[4] = lst.get(i).getFechai(); 
                vhb[5] = lst.get(i).getFechaf();
                vhb[6] = lst.get(i).getDiasr();
                vhb[7] = lst.get(i).getEstancia();
                vhb[8] = lst.get(i).getCoste();
                vhb[9] = lst.get(i).getEstadoR();
                
                dtm.addRow(vhb);
            }
            
            this.tbreserva.setModel(dtm);   
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        llenaLista();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JTextField fechaf;
    private javax.swing.JTextField fechai;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbreserva;
    // End of variables declaration//GEN-END:variables
}
